import { useState, type ChangeEvent } from 'react'
import { Link } from 'react-router-dom'
import { projectPath } from '../lib/projects'
import type { Translation, TranslationSegment } from '../types/translation'
import { useWorkspace } from '../state/WorkspaceContext'
import { applicableTerms, sourceUsesTerm, terminologyPatches, isTerminologyIssue } from '../lib/terminology'
import { applyTerminologyPatches, applyTranslationResult, parseTranslationResult, translationPrompt } from '../lib/translationFlow'
import { download, readTextFile, safeName } from '../lib/files'
import { TERM_CATEGORIES } from '../lib/model'
import AutoTranslationPanel from './AutoTranslationPanel'
import { Badge, Button, Modal } from './UI'
export default function GlossaryReviewTools({doc,segment,dirty}:{doc:Translation;segment:TranslationSegment;dirty:boolean}){
  const {state,run,busy,notify}=useWorkspace(),[patches,setPatches]=useState<ReturnType<typeof terminologyPatches>|null>(null),[selection,setSelection]=useState<string[]>([]),[request,setRequest]=useState(false),[importing,setImporting]=useState(false),[result,setResult]=useState(''),[parsed,setParsed]=useState<ReturnType<typeof parseTranslationResult>|null>(null)
  const terms=applicableTerms(doc,state.glossary), relevant=terms.filter(t=>sourceUsesTerm(segment.sourceText,t)), pending=doc.issues.filter(i=>i.status==='open'&&isTerminologyIssue(i)), changes=terminologyPatches(doc,state.glossary), readonly=doc.status==='FINALIZED'
  const glossaryPath=doc.domain?projectPath(doc.domain,'glossary'):'/glossary'
  const read=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{setResult(await readTextFile(file));setParsed(null)}catch(error){notify(error instanceof Error?error.message:'결과를 읽지 못했습니다.','error')}}
  const previewResult=()=>{try{setParsed(parseTranslationResult(result,doc))}catch(error){notify(error instanceof Error?error.message:'결과를 확인해 주세요.','error')}}
  return <><AutoTranslationPanel doc={doc} dirty={dirty}/><section className="panel glossary-review-tools">
    <div className="glossary-tools-heading"><div><h2>번역에 적용하는 기준 문서</h2><p>{doc.domain || '공통 용어집'} · 적용 용어 {terms.length}개 · 미처리 표기 이슈 {pending.length}개</p></div><div className="inline-actions"><Link className="button button--secondary button--small" to={glossaryPath}>프로젝트 용어집</Link><Button small disabled={busy||readonly||dirty||!changes.length} onClick={()=>{setPatches(changes);setSelection(changes.map(p=>p.segmentId))}}>표기 통일 미리보기 {changes.length > 0 ? `(${changes.length})` : ''}</Button></div></div>
    <details className="segment-reference"><summary>현재 구간의 기준 용어 · {relevant.length}개</summary>{relevant.length>0?<div className="segment-term-cards">{relevant.map(t=><div className="segment-term-card" key={t.id}><span>{TERM_CATEGORIES[t.category??'term']}</span><strong>{t.source} → {t.target}</strong>{!!t.variants?.length&&<small>피할 표기: {t.variants.join(' · ')}</small>}{t.note&&<p>{t.note}</p>}</div>)}</div>:<p className="muted">현재 구간에 연결된 용어가 없습니다. 모델이 원문에서 필요한 용어를 생성하고 다음 번역에 적용합니다.</p>}</details>
    {patches&&<Modal wide title="표기 통일 · 적용 전 확인" onClose={()=>{if(!busy)setPatches(null)}}><p className="modal-description">기존 번역에서 등록된 피할 표기를 기준 번역으로 바꿉니다. 문맥까지 반영하려면 모델로 다시 번역할 수 있습니다. 원문과 자막 시간은 유지됩니다.</p><div className="patch-list">{patches.map(p=><label className="patch-item" key={p.segmentId}><span><input type="checkbox" checked={selection.includes(p.segmentId)} onChange={e=>setSelection(ids=>e.target.checked?[...ids,p.segmentId]:ids.filter(id=>id!==p.segmentId))}/> 구간 {doc.segments.findIndex(s=>s.id===p.segmentId)+1}</span><div className="patch-comparison"><div><small>수정 전</small><p>{p.before}</p></div><div><small>수정 후</small><p>{p.after}</p></div></div></label>)}</div><div className="modal-actions"><Button variant="secondary" onClick={()=>setPatches(null)} disabled={busy}>취소</Button><Button disabled={busy||!selection.length} onClick={async()=>{if(await run(s=>applyTerminologyPatches(s,doc.id,patches.filter(p=>selection.includes(p.segmentId))),`${selection.length}개 구간의 표기를 통일했습니다. 문맥을 확인해 주세요.`))setPatches(null)}}>선택한 {selection.length}개 적용</Button></div></Modal>}
    <details className="panel manual-ai-fallback"><summary>수동으로 번역 요청·결과 가져오기</summary><p>다른 번역 도구에서도 같은 기준 문서를 사용할 수 있도록 요청 파일과 결과 가져오기를 제공합니다.</p><div className="inline-actions"><Button small variant="secondary" disabled={dirty} onClick={()=>setRequest(true)}>작품 용어집 포함 요청</Button><Button small variant="secondary" disabled={dirty||busy||readonly} onClick={()=>setImporting(true)}>수동 번역 JSON 가져오기</Button></div></details>
    {request&&<Modal wide title="작품 용어집 포함 번역 요청" onClose={()=>setRequest(false)}><p className="modal-description">외부 모델에서 생성한 JSON을 불러올 때 요청 규격이 필요하면 내려받으세요.</p><textarea className="request-prompt" aria-label="용어집 포함 번역 요청" readOnly value={translationPrompt(doc,state.glossary)}/><div className="modal-actions"><Button variant="secondary" onClick={()=>setRequest(false)}>닫기</Button><Button onClick={()=>download(translationPrompt(doc,state.glossary),`${safeName(doc.title)}-번역요청.txt`)}>요청 파일 다운로드</Button></div></Modal>}
    {importing&&<Modal wide title="수동 번역 결과 가져오기" onClose={()=>{if(!busy)setImporting(false)}}><p className="modal-description">API 연결 없이 번역한 JSON을 넣을 수 있습니다. 원문·구간 ID·버전을 확인한 후 번역만 갱신하고 용어집을 다시 검사합니다.</p><label className="button button--secondary">JSON 파일 선택<input className="sr-only" type="file" accept=".json" aria-label="번역 결과 JSON 파일" onChange={read}/></label><textarea className="request-prompt" aria-label="번역 결과 JSON" value={result} onChange={e=>{setResult(e.target.value);setParsed(null)}} placeholder="번역 결과 JSON을 붙여 넣으세요."/>{parsed&&<div className="import-note"><span><Badge>{parsed.length}개 구간 검증됨</Badge> · 번역을 갱신하면 기존 번역은 수정 이력에 보관됩니다.</span></div>}{parsed&&<div className="patch-list">{parsed.slice(0,3).map(p=><div className="patch-item" key={p.segmentId}><small>번역 미리보기</small><p>{p.after}</p></div>)}</div>}<div className="modal-actions"><Button variant="secondary" onClick={()=>setImporting(false)} disabled={busy}>취소</Button><Button variant="secondary" onClick={previewResult} disabled={!result||busy}>결과 미리보기</Button><Button disabled={!parsed||busy} onClick={async()=>{if(await run(s=>applyTranslationResult(s,doc.id,result),'번역 결과를 저장하고 용어집으로 다시 검사했습니다.')){setImporting(false);setResult('');setParsed(null)}}}>번역 반영·용어 검사</Button></div></Modal>}
  </section></>
}