const { test }=require('node:test');const assert=require('node:assert/strict');
const { emptyWorkspace, uid }=require('../src/lib/model.ts');
const { createDocument, editSegment, markReviewed }=require('../src/lib/actions.ts');
const { applicableTerms, normalizeKnownVariants, terminologyPatches, isTerminologyIssue }=require('../src/lib/terminology.ts');
const { applyTerminologyPatches, translationPrompt, parseTranslationResult, applyTranslationResult }=require('../src/lib/translationFlow.ts');
const { putGlossaryTerm, parseGlossaryCSV }=require('../src/lib/glossary.ts');
const { parseSubtitles, serializeSubtitles }=require('../src/lib/subtitles.ts');
const { validateWorkspace, parseBackup }=require('../src/lib/validation.ts');
const { backupText, makeCSV }=require('../src/lib/files.ts');
const { loadLiteraryExamples, DEMO_WORK, SUBTITLE_SOURCE }=require('../src/lib/literaryDemo.ts');
const term=(overrides={})=>({id:uid(),source:'Serin',target:'세린',sourceLang:'en',targetLang:'ko',severity:'warning',project:'별빛 서약',variants:['셀린','세린느'],category:'character',...overrides});
function sample(source='Serin met Serin.',target='세린은 셀린을 만났다.') {const state=emptyWorkspace();state.glossary=[term()];createDocument(state,{title:'회차',domain:'별빛 서약',sourceLang:'en',targetLang:'ko',contentType:'novel',pairs:[{source,target}]});return {state,doc:state.translations[0]};}
function output(doc,target='세린이 왔다.') {return JSON.stringify({format:'ian-translation-result',documentId:doc.id,segments:doc.segments.map(s=>({id:s.id,revision:s.revision,source:s.sourceText,target}))});}
test('project-specific glossary overrides global term without leaking into another work',()=>{const global=term({project:'',target:'세린'}),local=term({project:'다른 작품',target:'세리나'});assert.deepEqual(applicableTerms({sourceLang:'en',targetLang:'ko',domain:'다른 작품'},[global,local]),[local]);assert.deepEqual(applicableTerms({sourceLang:'en',targetLang:'ko',domain:'별빛 서약'},[global,local]),[global]);});
test('alias points to the same canonical entity',()=>{const {state,doc}=sample('The Silver Warden has arrived.','셀린이 왔다.');putGlossaryTerm(state,{...state.glossary[0],aliases:['The Silver Warden']});assert.equal(doc.issues.filter(i=>i.status==='open'&&isTerminologyIssue(i)).length,1);});
test('mixed spelling is flagged even when the canonical translation also appears',()=>{const {doc}=sample();const issue=doc.issues.find(i=>i.type==='표기 혼용');assert.ok(issue);assert.equal(issue.suggestedTargetText,'세린은 세린을 만났다.');});
test('canonical forms and longer variants are protected from substring replacements',()=>{assert.equal(normalizeKnownVariants('셀린과 린과 세린느',[term({target:'셀린',variants:['린','세린느']})]),'셀린과 셀린과 셀린');});
test('conflicting variants are not auto-replaced and replacements do not cascade',()=>{assert.equal(normalizeKnownVariants('Alex',[term({target:'알렉스',variants:['Alex']}),term({target:'알렉산더',variants:['Alex']})]),'Alex');assert.equal(normalizeKnownVariants('A',[term({target:'B',variants:['A']}),term({target:'C',variants:['B']})]),'B');});
test('English variants match whole words rather than parts of another name',()=>assert.equal(normalizeKnownVariants('Ann Annette',[term({target:'Anne',variants:['Ann']})]),'Anne Annette'));
test('batch normalization preserves source, creates history, clears review, and removes resolved glossary issues',()=>{const {state,doc}=sample();const seg=doc.segments[0];markReviewed(state,doc.id,seg.id,true);applyTerminologyPatches(state,doc.id,terminologyPatches(doc,state.glossary));assert.equal(seg.sourceText,'Serin met Serin.');assert.equal(seg.targetText,'세린은 세린을 만났다.');assert.equal(seg.history[0].text,'세린은 셀린을 만났다.');assert.equal(seg.reviewed,false);assert.equal(doc.issues.filter(i=>i.status==='open'&&isTerminologyIssue(i)).length,0);});
test('stale segment or changed glossary invalidates the entire patch preview',()=>{const {state,doc}=sample();let patches=terminologyPatches(doc,state.glossary);editSegment(state,doc.id,doc.segments[0].id,1,'셀린이 떠났다.');assert.throws(()=>applyTerminologyPatches(state,doc.id,patches),/바뀌었습니다/);patches=terminologyPatches(doc,state.glossary);state.glossary[0].target='세리나';assert.throws(()=>applyTerminologyPatches(state,doc.id,patches),/바뀌었습니다/);});
test('glossary update checks all unfinished episodes and revokes review where new issues appear',()=>{const {state,doc}=sample('Serin came.','세린이 왔다.');markReviewed(state,doc.id,doc.segments[0].id,true);putGlossaryTerm(state,{...state.glossary[0],target:'세리나',variants:['세린']});assert.equal(doc.segments[0].reviewed,false);assert.ok(doc.issues.some(i=>i.status==='open'&&i.type==='표기 혼용'));});
test('CSV glossary preserves project, aliases, variants and context',()=>{const t=term({aliases:['Lady Serin'],note:'단장. 부하는 존댓말.'});const csv=makeCSV([['source','target','source_language','target_language','project','category','aliases','variants','note'],[t.source,t.target,t.sourceLang,t.targetLang,t.project,t.category,t.aliases.join('|'),t.variants.join('|'),t.note]]);const [parsed]=parseGlossaryCSV(csv);assert.equal(parsed.project,t.project);assert.deepEqual(parsed.variants,t.variants);assert.equal(parsed.note,t.note);});
test('same source is valid in different works; duplicate source in same work is rejected',()=>{const state=emptyWorkspace();state.glossary=[term(),term({project:'다른 작품'})];validateWorkspace(state);state.glossary.push(term());assert.throws(()=>validateWorkspace(state),/중복 용어/);});
test('SRT import/export preserves timecodes, identifiers and multiline cue content',()=>{const parsed=parseSubtitles(SUBTITLE_SOURCE,'srt'),state=emptyWorkspace();createDocument(state,{title:'자막',domain:'작품',sourceLang:'en',targetLang:'ko',contentType:'subtitle',subtitle:parsed.subtitle,pairs:parsed.pairs.map(p=>({...p,target:p.source}))});assert.equal(serializeSubtitles(state.translations[0]),SUBTITLE_SOURCE);assert.deepEqual(parseBackup(backupText(state)),state);});
test('VTT preserves header, cue settings, identifiers, notes and style blocks',()=>{const input='WEBVTT example\n\nSTYLE\n::cue { color: lime; }\n\nNOTE first\n\nintro\n00:01.000 --> 00:03.000 align:start position:10%\n<v Serin>Hello.</v>\n\nNOTE last\n';const p=parseSubtitles(input,'vtt');const state=emptyWorkspace();createDocument(state,{title:'vtt',domain:'작품',sourceLang:'en',targetLang:'ko',contentType:'subtitle',subtitle:p.subtitle,pairs:p.pairs.map(c=>({...c,target:c.source}))});assert.equal(serializeSubtitles(state.translations[0]),input);});
test('invalid or reversed subtitle timings and empty cues are rejected',()=>{assert.throws(()=>parseSubtitles('1\n00:00:05,000 --> 00:00:01,000\nHi','srt'),/종료/);assert.throws(()=>parseSubtitles('1\n00:99:05,000 --> 00:99:07,000\nHi','srt'),/분·초/);assert.throws(()=>parseSubtitles('1\n00:00:01,000 --> 00:00:03,000','srt'),/내용/);});
test('subtitle export rejects blank translated cues or structural blank lines',()=>{const state=emptyWorkspace(),p=parseSubtitles('1\n00:00:01,000 --> 00:00:03,000\nHello.','srt');createDocument(state,{title:'test',domain:'',sourceLang:'en',targetLang:'ko',subtitle:p.subtitle,pairs:p.pairs});assert.throws(()=>serializeSubtitles(state.translations[0]),/비어/);state.translations[0].segments[0].targetText='가\n\n나';assert.throws(()=>serializeSubtitles(state.translations[0]),/빈 줄/);});
test('translation request includes matching terms, relationship notes and stable segment identity',()=>{const {state,doc}=sample();state.glossary[0].note='카엘은 세린에게 존댓말.';state.glossary.push(term({project:'다른 작품',target:'잘못된 작품용어'}));const text=translationPrompt(doc,state.glossary);assert.ok(text.includes('카엘은 세린에게 존댓말.'));assert.ok(text.includes('세린느'));assert.ok(text.includes(doc.segments[0].id));assert.ok(!text.includes('잘못된 작품용어'));});
test('translation result application updates targets and rechecks glossary without changing originals',()=>{const {state,doc}=sample('Serin came.','');const source=doc.segments[0].sourceText;applyTranslationResult(state,doc.id,output(doc));assert.equal(doc.segments[0].sourceText,source);assert.equal(doc.segments[0].targetText,'세린이 왔다.');assert.equal(doc.segments[0].originalTargetText,'');assert.equal(doc.issues.filter(i=>i.status==='open').length,0);});
test('wrong document, changed source and old revisions reject translation result',()=>{const {doc}=sample();let raw=JSON.parse(output(doc));raw.documentId='other';assert.throws(()=>parseTranslationResult(JSON.stringify(raw),doc),/문서 ID/);raw=JSON.parse(output(doc));raw.segments[0].source='other';assert.throws(()=>parseTranslationResult(JSON.stringify(raw),doc),/문서가 수정/);raw=JSON.parse(output(doc));raw.segments[0].revision=5;assert.throws(()=>parseTranslationResult(JSON.stringify(raw),doc),/문서가 수정/);});
test('all story examples can be normalized with the same scoped glossary while subtitle timing stays intact',()=>{const state=emptyWorkspace();loadLiteraryExamples(state);assert.equal(state.translations.length,3);assert.equal(state.glossary.length,8);assert.equal(state.translations.flatMap(d=>d.segments).length,20);let count=0;for(const doc of state.translations){const times=doc.segments.map(s=>s.cue?.timing),patches=terminologyPatches(doc,state.glossary);count+=patches.length;applyTerminologyPatches(state,doc.id,patches);assert.deepEqual(doc.segments.map(s=>s.cue?.timing),times);assert.equal(doc.issues.filter(i=>i.status==='open'&&isTerminologyIssue(i)).length,0);}assert.equal(count,18);assert.ok(state.translations.every(d=>d.domain===DEMO_WORK));validateWorkspace(state);});


test('subtitle structure compares CRLF, formatting, voice and timestamp tags', () => {
 const { subtitleTextProblems } = require('../src/lib/subtitles.ts')
 assert.deepEqual(subtitleTextProblems('<v Mira><i>Hello.</i>\r\n<00:00:02.000>Wait.', '<v Mira><i>안녕.</i>\n<00:00:02.000>기다려.'), [])
 assert.equal(subtitleTextProblems('<i>Hello.</i>', '<b>안녕.</b>')[0].type, '자막 태그')
 assert.equal(subtitleTextProblems('Hello.\nWait.', '안녕. 기다려.')[0].type, '자막 줄바꿈')
})
test('manual subtitle structure violations remain visible review issues', () => {
 const { inspectSegment } = require('../src/lib/rules.ts')
 const { doc } = sample('<i>Hello.</i>\nWait.', '안녕. 기다려.')
 doc.contentType = 'subtitle'
 assert.deepEqual(inspectSegment(doc.segments[0], doc, []).map(issue => issue.type), ['자막 줄바꿈', '자막 태그'])
})
