import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { projectPath, sameProject } from '../lib/projects'
import { useWorkspace } from '../state/WorkspaceContext'
import { average, canSubmit, CRITERIA, formatDate, LANGUAGES, type Criterion, type Evaluation, type Ratings } from '../lib/model'
import { saveEvaluation } from '../lib/actions'
import { exportEvaluations } from '../lib/files'
import { Badge, Button, ConfirmDialog, MissingDocument, UnsavedGuard } from '../components/UI'
import Icon from '../components/Icon'
const criteriaHelp: Record<Criterion, string> = { accuracy: '원문의 의미를 빠뜨리거나 왜곡하지 않았나요?', fluency: '번역 언어로 읽을 때 자연스럽고 명확한가요?', terminology: '용어와 표현이 문맥 안에서 일관적인가요?' }
export default function EvaluationDetailPage() {
  const { evaluationId, project } = useParams(), { state } = useWorkspace(), evaluation = state.evaluations.find(e => e.id === evaluationId && (!project || sameProject(e.project, project)))
  return evaluation ? <EvaluationWorkspace key={evaluation.id} evaluation={evaluation} project={project} /> : <MissingDocument title="평가를 찾을 수 없습니다" to={project ? projectPath(project, 'evaluations') : '/evaluations'} />
}
function EvaluationWorkspace({ evaluation: e, project }: { evaluation: Evaluation; project?: string }) {
  const { run, busy } = useWorkspace(), [ratings, setRatings] = useState<[Ratings, Ratings]>(structuredClone(e.ratings)), [preference, setPreference] = useState(e.preference), [comment, setComment] = useState(e.comment), [reviewer, setReviewer] = useState(e.reviewer), [error, setError] = useState(''), [submitting, setSubmitting] = useState(false)
  const submitted = e.status === 'SUBMITTED'
  const patch = { ratings, preference, comment, reviewer }
  const dirty = !submitted && (JSON.stringify(ratings) !== JSON.stringify(e.ratings) || preference !== e.preference || comment !== e.comment || reviewer !== e.reviewer)
  const scored = ratings.flatMap(r => Object.values(r)).filter(Boolean).length
  const submit = () => { const problem = canSubmit({ ...e, ...patch }); if (problem) { setError(problem); return } setError(''); setSubmitting(true) }
  return <div className="stack-lg evaluation-detail"><UnsavedGuard dirty={dirty} /><div className="review-heading"><div><Link className="back-link" to={project ? projectPath(project, 'evaluations') : '/evaluations'}><Icon name="left" size={15} />평가 목록</Link><div className="title-row"><h1>{e.title}</h1>{e.isDemo && <Badge>예제</Badge>}</div><div className="document-meta"><span>{LANGUAGES[e.sourceLang]}<Icon name="arrow" size={13} />{LANGUAGES[e.targetLang]}</span><Badge tone={submitted ? 'green' : 'purple'}>{submitted ? '제출 완료' : '블라인드 평가 중'}</Badge><span>{submitted ? formatDate(e.submittedAt!, true) : `${scored} / 6개 항목 평가`}</span></div></div><div className="heading-actions">{submitted ? <Button variant="secondary" icon="download" onClick={() => exportEvaluations([e])}>결과 CSV</Button> : <><Button variant="secondary" icon="save" disabled={!dirty || busy} onClick={() => run(s => saveEvaluation(s, e.id, patch, false), '평가를 임시 저장했습니다.')}>임시 저장</Button><Button icon="check" disabled={busy} onClick={submit}>평가 제출</Button></>}</div></div>
    {submitted && <section className="evaluation-result-banner"><span className="result-check"><Icon name="check" size={28} /></span><div><div className="eyebrow">EVALUATION COMPLETED</div><h2>{e.preference === 'tie' ? '두 번역을 동등하게 평가했습니다.' : e.preference === 'abstain' ? '최종 선호도 판단을 보류했습니다.' : `번역 ${e.preference}를 더 선호했습니다.`}</h2><p>평가자: {e.reviewer || '이름 미입력'} · 이제 각 번역의 이름과 평가 결과를 확인할 수 있습니다.</p></div></section>}
    <article className="panel evaluation-source"><div className="text-panel-heading"><span><span className="text-language">{e.sourceLang.toUpperCase()}</span>공통 원문</span><Badge>두 번역의 동일한 기준</Badge></div><p lang={e.sourceLang}>{e.sourceText}</p></article>
    {!submitted && <div className="evaluation-scoring-note"><Icon name="eye" size={18} /><span>이름을 가린 두 번역을 독립적으로 평가해 주세요.</span><span>1점 부적절 · 3점 보통 · 5점 우수</span></div>}
    <div className="evaluation-candidates">{e.candidates.map((candidate, index) => { const letter = index === 0 ? 'A' : 'B'; return <section className={`panel candidate-card candidate-${letter}`} key={letter}><div className="candidate-heading"><div><span className="candidate-letter">{letter}</span><div><h2>번역 {letter}</h2><span>{submitted ? candidate.label : '후보 이름 비공개'}</span></div></div>{submitted ? <div className="candidate-average">{average(e.ratings[index])}<span>/ 5.0</span></div> : <Icon name="lock" size={18} />}</div><p className="candidate-content" lang={e.targetLang}>{candidate.text}</p><div className="candidate-ratings">{(Object.entries(CRITERIA) as [Criterion, string][]).map(([key, label]) => <fieldset className="rating-row" key={key}><legend>{label}<span>{criteriaHelp[key]}</span></legend><div className="rating-options">{[1, 2, 3, 4, 5].map(value => <label key={value} className={ratings[index][key] === value ? 'selected' : ''}><input type="radio" name={`${letter}-${key}`} aria-label={`${letter} ${label} ${value}점`} checked={ratings[index][key] === value} disabled={submitted || busy} onChange={() => { setRatings(previous => previous.map((r, i) => i === index ? { ...r, [key]: value } : r) as [Ratings, Ratings]); setError('') }} />{value}</label>)}</div></fieldset>)}</div></section> })}</div>
    <section className="panel form-panel preference-panel"><div className="section-title"><h2>종합 의견</h2><Badge>{submitted ? '제출한 의견' : '마지막 단계'}</Badge></div><fieldset className="preference-field"><legend>전체적으로 어떤 번역을 더 선호하나요?</legend><div className="preference-options">{([{ value: 'A', title: '번역 A', subtitle: 'A가 더 적절해요' }, { value: 'tie', title: '동등함', subtitle: '두 번역이 비슷해요' }, { value: 'B', title: '번역 B', subtitle: 'B가 더 적절해요' }, { value: 'abstain', title: '판단 보류', subtitle: '추가 맥락이 필요해요' }] as const).map(o => <label key={o.value} className={preference === o.value ? 'selected' : ''}><input type="radio" name="preference" value={o.value} checked={preference === o.value} disabled={submitted || busy} onChange={() => { setPreference(o.value); setError('') }} /><span><strong>{o.title}</strong><small>{o.subtitle}</small></span></label>)}</div></fieldset><div className="form-grid"><label className="field field--wide">평가 의견 (선택)<textarea value={comment} maxLength={3000} onChange={event => setComment(event.target.value)} disabled={submitted || busy} rows={4} placeholder="판단의 근거, 아쉬운 표현, 개선할 부분을 남겨 주세요." /></label><label className="field">평가자 이름 (선택)<input value={reviewer} maxLength={80} onChange={event => setReviewer(event.target.value)} disabled={submitted || busy} placeholder="이름 또는 닉네임" /></label></div></section>
    {error && <div className="inline-error" role="alert"><Icon name="alert" size={17} />{error}</div>}{!submitted && <div className="form-footer"><span className={dirty ? 'orange-text' : ''}><Icon name={dirty ? 'edit' : 'check'} size={16} />{dirty ? '저장하지 않은 변경이 있습니다. 임시 저장하거나 제출해 주세요.' : '저장된 평가 상태입니다.'}</span><Button icon="check" onClick={submit} disabled={busy}>평가 제출</Button></div>}
    {submitted && <p className="footnote">점수는 평가자 1명의 세 항목에 대한 단순 평균입니다. 통계적 우열이나 객관적인 품질 인증을 의미하지 않습니다. 제출 결과는 수정하지 않으며, 새 평가를 만들어 다시 비교할 수 있습니다.</p>}
    {submitting && <ConfirmDialog title="평가를 제출할까요?" description="제출하면 A/B의 후보 이름이 공개되고 점수와 의견은 읽기 전용으로 전환됩니다. 제출 후에는 수정할 수 없습니다." danger={false} confirmLabel="제출하고 후보 공개" busy={busy} onClose={() => setSubmitting(false)} onConfirm={async () => { if (await run(s => saveEvaluation(s, e.id, patch, true), '평가를 제출했습니다. 후보 이름을 공개합니다.')) setSubmitting(false) }} />}
  </div>
}
