import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { projectPath, sameProject } from '../lib/projects'
import { useWorkspace } from '../state/WorkspaceContext'
import { average, logActivity, relativeTime, type Evaluation } from '../lib/model'
import { exportEvaluations } from '../lib/files'
import { Badge, Button, ConfirmDialog, EmptyState, PageHeading } from '../components/UI'
import Icon from '../components/Icon'
export default function EvaluationsPage() {
  const { state, run, busy } = useWorkspace(), { project } = useParams(), [filter, setFilter] = useState('all'), [query, setQuery] = useState(''), [deleting, setDeleting] = useState<Evaluation | null>(null)
  const projectItems = state.evaluations.filter(e => project ? sameProject(e.project, project) : !e.project)
  const newPath = project ? projectPath(project, 'evaluations/new') : '/'
  const detailPath = (id: string) => project ? projectPath(project, `evaluation/${id}`) : `/evaluation/${id}`
  const items = projectItems.filter(e => (filter === 'all' || e.status === filter) && e.title.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
  return <div className="stack-lg"><PageHeading eyebrow="BLIND EVALUATION" title="같은 원문, 다른 번역." description="이름 대신 문장에 집중하세요. 두 번역을 같은 기준으로 비교하고 판단을 기록합니다."><Button variant="secondary" icon="download" disabled={!items.length} onClick={() => exportEvaluations(items)}>CSV 내보내기</Button><Link className="button button--primary" to={newPath}><Icon name="plus" size={17} />{project ? '새 평가 만들기' : '프로젝트 선택'}</Link></PageHeading>
    <div className="evaluation-intro"><span className="evaluation-intro-icon"><Icon name="compare" size={27} /></span><div><h3>순서는 무작위로, 기준은 일관되게.</h3><p>평가 생성 시 A/B 순서를 정하고 제출 전까지 후보 이름을 가립니다. 정확성·자연스러움·용어 일관성을 각각 1~5점으로 평가합니다.</p></div><Badge tone="purple">개인 평가 도구</Badge></div>
    <section><div className="list-toolbar"><div className="tabs"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>전체 <span>{projectItems.length}</span></button><button className={filter === 'DRAFT' ? 'active' : ''} onClick={() => setFilter('DRAFT')}>평가 대기</button><button className={filter === 'SUBMITTED' ? 'active' : ''} onClick={() => setFilter('SUBMITTED')}>제출 완료</button></div><label className="search-input"><Icon name="search" size={17} /><input aria-label="평가 검색" value={query} onChange={e => setQuery(e.target.value)} placeholder="평가 제목 검색" /></label></div>{items.length ? <div className="evaluation-grid">{items.map(e => <article className="evaluation-card" key={e.id}><div className="evaluation-card-top"><span className="comparison-symbol"><span>A</span><Icon name="compare" size={14} /><span>B</span></span><Badge tone={e.status === 'SUBMITTED' ? 'green' : 'purple'}>{e.status === 'SUBMITTED' ? '제출 완료' : '평가 대기'}</Badge></div><Link to={detailPath(e.id)}><h2>{e.title}</h2><p className="evaluation-excerpt">{e.sourceText}</p></Link><div className="evaluation-card-meta"><span>{e.sourceLang.toUpperCase()} <Icon name="arrow" size={12} /> {e.targetLang.toUpperCase()}</span>{e.isDemo && <Badge>예제</Badge>}<span>{relativeTime(e.updatedAt)}</span></div>{e.status === 'SUBMITTED' ? <div className="evaluation-card-result"><span>A <strong>{average(e.ratings[0])}</strong></span><span>B <strong>{average(e.ratings[1])}</strong></span><small>선호: {e.preference === 'tie' ? '동등' : e.preference === 'abstain' ? '판단 보류' : e.preference}</small></div> : <div className="evaluation-card-result"><Icon name="eye" size={15} /><small>후보 이름은 제출 후 공개됩니다</small></div>}<div className="evaluation-card-footer"><Link className="text-link" to={detailPath(e.id)}>{e.status === 'SUBMITTED' ? '평가 결과 보기' : '평가 이어서 하기'}<Icon name="arrow" size={16} /></Link><button className="icon-button" aria-label={`${e.title} 평가 삭제`} onClick={() => setDeleting(e)}><Icon name="trash" size={16} /></button></div></article>)}</div> : <section className="panel"><EmptyState icon="compare" title={state.evaluations.length ? '조건에 맞는 평가가 없습니다' : '첫 번째 비교 평가를 만들어 보세요'} description="원문 하나와 번역 후보 두 개를 등록하면 블라인드 평가를 시작할 수 있습니다."><Link className="button button--primary" to={newPath}>{project ? '평가 만들기' : '프로젝트 선택'}</Link></EmptyState></section>}</section>
    <p className="footnote"><Icon name="help" size={15} />로컬 A/B 표시는 화면상의 이름 가림입니다. 다중 평가자 배정이나 데이터 접근을 통제하는 보안 블라인드는 제공하지 않습니다.</p>
    {deleting && <ConfirmDialog title="이 평가를 삭제할까요?" description={`“${deleting.title}”의 번역 후보와 점수, 의견이 삭제됩니다. 원본 번역 문서에는 영향을 주지 않습니다.`} busy={busy} onClose={() => setDeleting(null)} onConfirm={async () => { if (await run(s => { s.evaluations = s.evaluations.filter(e => e.id !== deleting.id); logActivity(s, `“${deleting.title}” 평가를 삭제했습니다.`) }, '평가를 삭제했습니다.')) setDeleting(null) }} />}</div>
}
