import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useWorkspace } from '../state/WorkspaceContext'
import { applicableTerms, isTerminologyIssue, terminologyPatches } from '../lib/terminology'
import { DEMO_WORK, hasLiteraryExamples, loadLiteraryExamples } from '../lib/literaryDemo'
import { Badge, Button, ConfirmDialog, Modal } from '../components/UI'
import DocumentTable from '../components/DocumentTable'
import Icon from '../components/Icon'
import { AI_PROVIDERS } from '../lib/aiTypes'
import { createProject, deleteProject, projectNames, projectPath, renameProject, sameProject } from '../lib/projects'
import { deleteUIProject, renameUIProject } from '../lib/uiState'
export default function HomePage(){
  const {state,run,busy}=useWorkspace(), navigate=useNavigate(), {project}=useParams()
  const works=projectNames(state), [newProject,setNewProject]=useState(''), [renaming,setRenaming]=useState(false), [renamed,setRenamed]=useState(''), [deleting,setDeleting]=useState(false)
  const work=project??works[0]??'', docs=state.translations.filter(d=>sameProject(d.domain,work)), issues=docs.flatMap(d=>d.issues.filter(i=>i.status==='open'&&isTerminologyIssue(i)).map(i=>({doc:d,issue:i})))
  const terms=docs.length?applicableTerms(docs[0],state.glossary):state.glossary.filter(t=>sameProject(t.project,work))
  const featuredTerm=terms.find(t=>t.category==='character')??terms[0]
  const fixable=docs.filter(d=>d.status!=='FINALIZED').reduce((n,d)=>n+terminologyPatches(d,state.glossary).length,0)
  const workModel=state.aiProjects?.find(c=>sameProject(c.project,work))
  const addProject=async(e:React.FormEvent)=>{e.preventDefault();const name=newProject.trim();if(await run(s=>{createProject(s,name)},'프로젝트를 만들었습니다.')){setNewProject('');navigate(projectPath(name))}}
  return <div className="stack-lg consistency-home"><div className="dashboard-heading"><div><div className="eyebrow">STORY & SUBTITLE CONSISTENCY</div><h1>{project?`${project} 작업 공간`:'프로젝트별 번역 작업'}</h1><p>회차가 바뀌어도 이름과 호칭이 흔들리지 않도록.</p></div><div className="inline-actions">{project&&<><Button variant="secondary" onClick={()=>{setRenamed(project);setRenaming(true)}}>이름 변경</Button><Button variant="secondary" onClick={()=>setDeleting(true)}>프로젝트 삭제</Button></>}{work&&<Link to={projectPath(work,'documents/new')} className="button button--primary"><Icon name="plus" size={18}/>원고·자막 가져오기</Link>}</div></div>
    <section className="consistency-intro"><div><span className="eyebrow">TRANSLATE WITH A STORY BIBLE</span><h2>용어집을 번역의 기준으로.</h2><p>모델이 원문에서 용어와 맥락을 만들고 검증합니다. 같은 기준 문서를 읽어 모든 회차와 자막을 번역합니다.</p></div><ol><li><strong>01</strong><span>모델 용어집 생성·검증</span></li><li><strong>02</strong><span>기준 문서로 모델 번역</span></li><li><strong>03</strong><span>모델 재검증 · 결과 저장</span></li></ol></section>
    <section className="panel work-overview"><div className="panel-header"><div className="section-title"><h2>작품 작업 공간</h2><Badge>{works.length}개 작품</Badge></div></div><form className="project-create-form" onSubmit={addProject}><label className="field">새 프로젝트 이름<input required maxLength={80} value={newProject} onChange={e=>setNewProject(e.target.value)} placeholder="예: 별빛 서약" /></label><Button type="submit" disabled={busy||!newProject.trim()||works.some(w=>sameProject(w,newProject))} icon="plus">프로젝트 만들기</Button></form>{works.length?<div className="project-list">{works.map(name=>{const count=state.translations.filter(d=>sameProject(d.domain,name)).length;const config=state.aiProjects?.find(c=>sameProject(c.project,name));return <Link key={name} to={projectPath(name)} className={sameProject(work,name)?'active':''}><strong>{name}</strong><span>문서 {count}개 · {config?`${AI_PROVIDERS[config.provider].label} / ${config.model}`:'모델 미설정'}</span></Link>})}</div>:<p className="muted">프로젝트를 만든 뒤 원고·자막, 용어집, 모델을 추가하세요.</p>}{work&&<><div className="consistency-stats"><div><span>등록된 회차·자막</span><strong>{docs.length}<small>개</small></strong></div><div><span>작품의 기준 용어</span><strong>{terms.length}<small>개</small></strong></div><div><span>확인이 필요한 표기</span><strong>{issues.length}<small>건</small></strong></div><div><span>수정안이 있는 구간</span><strong>{fixable}<small>개</small></strong></div></div><div className="work-actions"><Link to={projectPath(work,'glossary')} className="button button--secondary"><Icon name="book" size={17}/>프로젝트 용어집 열기</Link><Link to={projectPath(work,'models')} className="button button--secondary">{workModel?'작품 모델 설정 보기':'작품 모델 설정'}</Link><Link to={`${projectPath(work,'documents/new')}?type=subtitle`} className="text-link">이 작품의 자막 추가 →</Link></div></>}</section>
    {!project&&state.evaluations.some(e=>!e.project)&&<section className="panel"><div className="panel-header"><h2>프로젝트 미지정 평가</h2><Link className="text-link" to="/evaluations">기존 평가 보기 →</Link></div><p className="muted">이전에 만든 평가는 기존 평가 목록에서 확인할 수 있습니다.</p></section>}
    {work&&<><div className="consistency-columns"><section className="panel"><div className="panel-header"><h2>흔들리는 표기부터 확인</h2><Badge tone="orange">{issues.length}</Badge></div>{issues.length?<div className="consistency-issues">{issues.slice(0,5).map(({doc,issue})=><Link key={issue.id} to={`${projectPath(work,`review/${doc.id}`)}?segment=${issue.segmentId}`}><span className="consistency-term">{issue.sourceQuote}<Icon name="arrow" size={14}/><strong>{state.glossary.find(t=>t.id===issue.termId)?.target??'기준 번역 확인'}</strong></span><span>{doc.title}</span><small>{issue.reason}</small></Link>)}</div>:<div className="compact-empty"><Icon name="check" size={24}/><strong>등록된 기준과 다른 표기가 없습니다</strong><p>모델 번역은 원문 전체를 검증한 용어집을 기준으로 진행합니다.</p></div>}</section>
    <section className="panel story-guide"><h2>이름뿐 아니라 관계도 기억하게</h2><p>별칭, 호칭, 반복 표현을 같은 작품에 묶어 관리합니다.</p>{featuredTerm?<div className="story-term-example"><span>원어</span><strong>{featuredTerm.source}</strong><span>기준 번역</span><strong>{featuredTerm.target}</strong><span>피할 표기</span><strong>{featuredTerm.variants?.join(' · ')||'미등록'}</strong><span>맥락</span><p>{featuredTerm.note||'맥락 메모 없음'}</p></div>:<p className="muted">이 프로젝트에 등록된 용어가 없습니다.</p>}<Link className="text-link" to={projectPath(work,'glossary')}>작품 용어집 관리 →</Link>{!hasLiteraryExamples(state)&&<Button variant="secondary" disabled={busy} onClick={async()=>{if(await run(loadLiteraryExamples,'웹소설·자막 예제를 추가했습니다.'))navigate(projectPath(DEMO_WORK))}}>작품 예제로 살펴보기</Button>}</section></div>
    <section className="panel"><div className="panel-header"><h2>{work}의 원고·자막</h2><Link className="text-link" to={projectPath(work,'documents')}>이 작품의 전체 파일 보기 →</Link></div>{docs.length?<DocumentTable documents={docs}/>:<div className="compact-empty"><p>첫 원고나 자막을 가져오세요.</p></div>}</section></>}
    {project&&renaming&&<Modal title="프로젝트 이름 변경" onClose={()=>setRenaming(false)}><form className="modal-form" onSubmit={async e=>{e.preventDefault();const name=renamed.trim();if(await run(s=>{renameProject(s,project,name)},'프로젝트 이름을 변경했습니다.')){renameUIProject(project,name);setRenaming(false);navigate(projectPath(name))}}}><label className="field">새 프로젝트 이름<input autoFocus required maxLength={80} value={renamed} onChange={e=>setRenamed(e.target.value)} /></label><p className="modal-description">문서·용어집·모델 설정·평가의 프로젝트 이름을 함께 바꿉니다.</p><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setRenaming(false)} disabled={busy}>취소</Button><Button type="submit" disabled={busy||!renamed.trim()}>이름 변경</Button></div></form></Modal>}
    {project&&deleting&&<ConfirmDialog title="프로젝트를 삭제할까요?" description={`“${project}”의 문서 ${docs.length}개, 용어 ${state.glossary.filter(t=>sameProject(t.project,project)).length}개, 평가 ${state.evaluations.filter(e=>sameProject(e.project,project)).length}개와 모델 설정이 삭제됩니다. 필요한 자료는 먼저 JSON으로 백업해 주세요.`} busy={busy} onClose={()=>setDeleting(false)} onConfirm={async()=>{if(await run(s=>deleteProject(s,project),'프로젝트와 연결된 자료를 삭제했습니다.')){deleteUIProject(project);setDeleting(false);navigate('/')}}} />}
  </div>
}
