import { useEffect, useState, type ChangeEvent } from 'react'
import { useWorkspace } from '../state/WorkspaceContext'
import { readRecovery } from '../lib/database'
import { exportBackup, readTextFile } from '../lib/files'
import { parseBackup } from '../lib/validation'
import { formatDate, logActivity, type Workspace } from '../lib/model'
import { loadExamples } from '../lib/demo'
import { Badge, Button, ConfirmDialog, Modal, PageHeading } from '../components/UI'
import Icon from '../components/Icon'
import TestSetPanel from '../components/TestSetPanel'
import { Link } from 'react-router-dom'
export default function SettingsPage() {
  const { state, run, busy, notify } = useWorkspace(), [incoming, setIncoming] = useState<{ data: Workspace; name: string } | null>(null), [confirmation, setConfirmation] = useState(''), [reading, setReading] = useState(false), [hasRecovery, setHasRecovery] = useState(false), [removingDemo, setRemovingDemo] = useState(false)
  const [persistent, setPersistent] = useState<boolean | null>(null)
  useEffect(() => { readRecovery().then(v => setHasRecovery(!!v)).catch(() => {}); navigator.storage?.persisted?.().then(setPersistent).catch(() => {}) }, [])
  const loadFile = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; setReading(true)
    try { const data = parseBackup(await readTextFile(file)); setIncoming({ data, name: file.name }); setConfirmation('') }
    catch (error) { notify(error instanceof Error ? error.message : '백업을 읽을 수 없습니다.', 'error') }
    finally { setReading(false) }
  }
  const bytes = new TextEncoder().encode(JSON.stringify(state)).length
  const demoCount = state.translations.filter(d => d.isDemo).length + state.evaluations.filter(e => e.isDemo).length
  return <div className="stack-lg settings-page"><PageHeading eyebrow="WORKSPACE SETTINGS" title="데이터는 내가 관리합니다." description="이 브라우저에만 저장되는 작업 공간입니다. 소중한 작업은 정기적으로 파일로 백업해 주세요." />
    <Link to="/models" className="panel ai-settings-link"><span className="setting-icon purple"><Icon name="spark" size={24}/></span><span><strong>작품별 번역 모델 연결</strong><small>로컬 Ollama 모델과 작품별 번역 기준을 설정합니다.</small></span><Icon name="arrow" size={19}/></Link>
    <section className="storage-overview"><span className="storage-icon"><Icon name="shield" size={30} /></span><div><h2>브라우저 로컬 저장소</h2><p>IndexedDB · 계정이나 클라우드 동기화 없음</p></div><div className="storage-stats"><strong>{bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(2)} MB`}</strong><span>작업 데이터 / 앱 제한 8 MB</span></div><Badge tone="green">연결됨</Badge></section>
    <details className="panel setting-card"><summary>개발용 일반 테스트 세트</summary><TestSetPanel /></details>
    <div className="settings-grid"><section className="panel setting-card"><span className="setting-icon purple"><Icon name="download" size={24} /></span><h2>전체 데이터 백업</h2><p>문서, 수정 이력, 이슈, 평가 결과, 용어집을 하나의 JSON 파일에 담습니다. 복원용 원본은 JSON 백업입니다.</p><div className="backup-counts"><span>문서 <strong>{state.translations.length}</strong></span><span>평가 <strong>{state.evaluations.length}</strong></span><span>용어 <strong>{state.glossary.length}</strong></span></div><Button icon="download" onClick={() => { exportBackup(state); notify('JSON 백업 파일을 생성했습니다. 다운로드 폴더를 확인해 주세요.') }}>JSON 백업 다운로드</Button><small>최근 데이터 변경: {formatDate(state.updatedAt, true)}</small></section><section className="panel setting-card"><span className="setting-icon blue"><Icon name="upload" size={24} /></span><h2>백업에서 복원</h2><p>Ian에서 내보낸 JSON 백업을 선택하세요. 파일 형식을 검증한 뒤 내용을 확인하고 복원할 수 있습니다.</p><div className="restore-warning"><Icon name="alert" size={16} /><span>복원하면 현재 작업 공간 전체가 교체됩니다.<br />교체 직전 데이터는 복구용 사본으로 보관합니다.</span></div><label className={`button button--secondary ${busy || reading ? 'disabled' : ''}`}><Icon name="upload" size={17} />{reading ? '백업 검증 중…' : 'JSON 백업 파일 선택'}<input type="file" className="sr-only" accept=".json,application/json" aria-label="JSON 백업 파일 선택" disabled={busy || reading} onChange={loadFile} /></label><small>UTF-8 JSON · 최대 10 MB · v1 백업 형식</small></section></div>
    {hasRecovery && <section className="panel recovery-card"><Icon name="clock" size={23} /><div><h3>직전 복원 전 데이터가 보관되어 있습니다</h3><p>잘못된 파일을 복원했나요? 복구 사본을 내려받은 뒤 다시 복원해 주세요. 다음 복원 시 이 사본은 교체됩니다.</p></div><Button variant="secondary" small icon="download" onClick={async () => { try { const recovery = await readRecovery(); if (recovery) exportBackup(recovery); else notify('복구 사본이 없습니다.', 'info') } catch { notify('복구 사본을 읽지 못했습니다.', 'error') } }}>복구 사본 다운로드</Button></section>}
    <section className="panel settings-details"><div className="panel-header"><h2>저장과 백업 안내</h2><Icon name="help" size={18} /></div><div className="settings-detail-row"><div><h3>브라우저 데이터 삭제에 주의하세요</h3><p>캐시가 아니라 사이트 데이터를 삭제하면 작업 데이터도 사라집니다. 시크릿 모드에서는 창을 닫을 때 사라질 수 있습니다. 브라우저·프로필·접속 주소와 포트가 달라지면 별도 저장소가 열립니다.</p></div></div><div className="settings-detail-row"><div><h3>저장소 유지 요청</h3><p>브라우저가 허용하면 저장 공간 정리 시 자동 삭제될 가능성을 줄입니다. 허용 여부는 브라우저 정책에 따라 달라지며 백업을 대체하지 않습니다.</p></div><Button variant="secondary" small disabled={persistent === true || !navigator.storage?.persist} onClick={async () => { try { const allowed = await navigator.storage.persist(); setPersistent(allowed); notify(allowed ? '저장소 유지가 허용되었습니다. 그래도 정기 백업은 필요합니다.' : '브라우저가 유지 요청을 허용하지 않았습니다. JSON 백업을 이용해 주세요.', allowed ? 'success' : 'info') } catch { notify('이 환경에서는 유지 요청을 지원하지 않습니다.', 'info') } }}>{persistent ? '유지 허용됨' : '저장소 유지 요청'}</Button></div><div className="settings-detail-row"><div><h3>민감한 문서와 백업 파일</h3><p>모델 번역을 실행하면 원문과 용어 메모가 이 PC의 Ollama로 전달됩니다. 이전 백업의 외부 모델 설정은 읽을 수 있지만 로컬 모델을 다시 선택해야 번역할 수 있습니다. 사용자별 데이터 분리 기능은 없으므로 공유·공용 기기에서 작업 공간을 사용하지 마세요. 그 외 브라우저 저장소와 JSON 백업은 별도 암호화하지 않습니다. CSV는 수식 실행 방지를 위해 일부 셀 앞에 작은따옴표를 추가합니다.</p></div></div></section>
    <section className="panel demo-settings"><div><h3>예제로 기능 둘러보기</h3><p>예제 문서 3개, 평가 1개와 기본 용어를 불러옵니다. 기존 작업을 덮어쓰지 않습니다.</p></div>{demoCount ? <Button variant="secondary" small icon="trash" disabled={busy} onClick={() => setRemovingDemo(true)}>예제 문서·평가 정리</Button> : <Button variant="secondary" small icon="plus" disabled={busy} onClick={() => run(loadExamples, '예제를 불러왔습니다.')}>예제 불러오기</Button>}</section>
    {incoming && <Modal title="백업 내용을 확인해 주세요" onClose={() => { if (!busy) setIncoming(null) }}><div className="modal-form"><p className="modal-description"><strong>{incoming.name}</strong><br />백업 데이터 변경 시각: {formatDate(incoming.data.updatedAt, true)}</p><div className="backup-counts"><span>문서 <strong>{incoming.data.translations.length}</strong></span><span>평가 <strong>{incoming.data.evaluations.length}</strong></span><span>용어 <strong>{incoming.data.glossary.length}</strong></span></div><div className="restore-warning"><Icon name="alert" size={18} /><span>현재 데이터 전체를 이 백업으로 교체합니다. 교체 전 데이터는 복구 사본에 보관합니다.</span></div><label className="field">계속하려면 ‘복원’을 입력하세요<input autoFocus value={confirmation} onChange={e => setConfirmation(e.target.value)} placeholder="복원" /></label><div className="modal-actions"><Button variant="secondary" onClick={() => setIncoming(null)} disabled={busy}>취소</Button><Button disabled={busy || confirmation !== '복원'} onClick={async () => { if (await run(s => { Object.assign(s, structuredClone(incoming.data)); logActivity(s, 'JSON 백업에서 작업 공간을 복원했습니다.') }, '백업을 복원했습니다. 이전 데이터는 복구 사본으로 보관했습니다.', true)) { setIncoming(null); setHasRecovery(true) } }}>이 백업으로 복원</Button></div></div></Modal>}
    {removingDemo && <ConfirmDialog title="예제 문서와 평가를 정리할까요?" description={`예제 표시가 있는 ${demoCount}개 문서·평가를 삭제합니다. 예제에서 직접 수정한 내용도 삭제됩니다. 다른 문서에서 사용할 수 있으므로 용어집 항목은 유지합니다.`} busy={busy} onClose={() => setRemovingDemo(false)} onConfirm={async () => { if (await run(s => { s.translations = s.translations.filter(d => !d.isDemo); s.evaluations = s.evaluations.filter(e => !e.isDemo); logActivity(s, '예제 문서와 평가를 정리했습니다.') }, '예제 문서와 평가를 정리했습니다. 용어집은 유지했습니다.')) setRemovingDemo(false) }} />}
  </div>
}
